/**
 * Tests for GitignoreManager class
 */

import { promises as fs } from 'fs';
import * as path from 'path';
import { createGitignoreManager, GitignoreManager } from '../GitignoreManager';
import type { GitignoreConfig } from '../types';

// Mock fs module
jest.mock('fs', () => ({
  promises: {
    readFile: jest.fn(),
    writeFile: jest.fn(),
  },
}));

const mockFs = fs as jest.Mocked<typeof fs>;

describe('GitignoreManager', () => {
  const testBasePath = '/test/project';

  beforeEach(() => {
    jest.clearAllMocks();
    mockFs.readFile.mockResolvedValue('');
    mockFs.writeFile.mockResolvedValue(undefined);
  });

  describe('constructor and basic functionality', () => {
    it('should create with default config', () => {
      const manager = new GitignoreManager();
      expect(manager.isEnabled()).toBe(true);
    });

    it('should create with custom config', () => {
      const config: Partial<GitignoreConfig> = {
        enabled: false,
        commentPrefix: 'Custom',
      };
      const manager = new GitignoreManager(config);
      expect(manager.isEnabled()).toBe(false);
    });

    it('should use createGitignoreManager factory', () => {
      const manager = createGitignoreManager({ enabled: true });
      expect(manager.isEnabled()).toBe(true);
    });
  });

  describe('updateGitignore', () => {
    it('should do nothing when disabled', async () => {
      const manager = new GitignoreManager({ enabled: false });
      const result = await manager.updateGitignore(['.cursor/rules/test.mdc']);

      expect(result.success).toBe(true);
      expect(result.added).toEqual([]);
      expect(result.messages).toEqual(['GitignoreManager is disabled']);
      expect(mockFs.readFile).not.toHaveBeenCalled();
    });

    it('should create .gitignore if it does not exist', async () => {
      mockFs.readFile
        .mockRejectedValueOnce({ code: 'ENOENT' }) // .gitignore doesn't exist
        .mockResolvedValueOnce('') // Return empty after creation
        .mockResolvedValueOnce('') // .rulesetkeep doesn't exist
        .mockResolvedValueOnce(''); // .rulesetignore doesn't exist

      const manager = new GitignoreManager({}, testBasePath);
      const result = await manager.updateGitignore(['.cursor/rules/test.mdc']);

      expect(mockFs.writeFile).toHaveBeenCalledWith(
        path.join(testBasePath, '.gitignore'),
        '',
        'utf8'
      );
      expect(result.success).toBe(true);
    });

    it('should add generated files to .gitignore', async () => {
      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.gitignore')) {
          return '# Existing content\nnode_modules/\n';
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      const result = await manager.updateGitignore([
        '.cursor/rules/test.mdc',
        '.windsurf/rules/test.md',
      ]);

      expect(result.success).toBe(true);
      expect(result.added).toEqual([
        '.cursor/rules/test.mdc',
        '.windsurf/rules/test.md',
      ]);

      const writeCall = mockFs.writeFile.mock.calls.find(
        (call) => call[0] === path.join(testBasePath, '.gitignore')
      );
      expect(writeCall).toBeDefined();
      const writtenContent = writeCall![1] as string;
      expect(writtenContent).toContain('# Existing content');
      expect(writtenContent).toContain('# START Rulesets Generated Files');
      expect(writtenContent).toContain('.cursor/rules/test.mdc');
      expect(writtenContent).toContain('.windsurf/rules/test.md');
    });

    it('should update existing managed block', async () => {
      const existingGitignore = `# Existing content
node_modules/

# START Rulesets Generated Files
# Generated by Rulesets - do not edit manually
.cursor/rules/old.mdc
# END Rulesets Generated Files

dist/`;

      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.gitignore')) {
          return existingGitignore;
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      const result = await manager.updateGitignore(['.cursor/rules/new.mdc']);

      expect(result.success).toBe(true);

      const writeCall = mockFs.writeFile.mock.calls.find(
        (call) => call[0] === path.join(testBasePath, '.gitignore')
      );
      const writtenContent = writeCall![1] as string;
      expect(writtenContent).toContain('.cursor/rules/old.mdc');
      expect(writtenContent).toContain('.cursor/rules/new.mdc');
    });

    it('should respect override files', async () => {
      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.gitignore')) {
          return 'node_modules/\n';
        }
        if (filePath.endsWith('.rulesetkeep')) {
          return '.cursor/rules/important.mdc\n';
        }
        if (filePath.endsWith('.rulesetignore')) {
          return '*.tmp\n';
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      const result = await manager.updateGitignore([
        '.cursor/rules/important.mdc', // Should be kept
        '.cursor/rules/normal.mdc', // Should be ignored
        'temp.tmp', // Should be ignored by .rulesetignore
      ]);

      expect(result.success).toBe(true);
      expect(result.kept).toContain('.cursor/rules/important.mdc');
      expect(result.added).toContain('.cursor/rules/normal.mdc');
      expect(result.added).toContain('temp.tmp');
    });

    it('should handle errors gracefully', async () => {
      mockFs.readFile.mockRejectedValue(new Error('Permission denied'));

      const manager = new GitignoreManager({}, testBasePath);
      const result = await manager.updateGitignore(['.cursor/rules/test.mdc']);

      expect(result.success).toBe(false);
      expect(result.messages[0]).toContain('Failed to update .gitignore');
    });

    it('should not write if content unchanged', async () => {
      const existingGitignore = `# START Rulesets Generated Files
# Generated by Rulesets - do not edit manually
.cursor/rules/test.mdc
# END Rulesets Generated Files`;

      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.gitignore')) {
          return existingGitignore;
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      await manager.updateGitignore(['.cursor/rules/test.mdc']);

      // Should only be called once to create the file if it doesn't exist
      expect(mockFs.writeFile).toHaveBeenCalledTimes(0);
    });
  });

  describe('readOverrides', () => {
    it('should read .rulesetkeep and .rulesetignore files', async () => {
      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.rulesetkeep')) {
          return '.cursor/rules/important.mdc\n# Comment\n.windsurf/rules/keep.md';
        }
        if (filePath.endsWith('.rulesetignore')) {
          return '*.tmp\ndist/';
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      const overrides = await manager.readOverrides();

      expect(overrides.keep).toEqual([
        '.cursor/rules/important.mdc',
        '.windsurf/rules/keep.md',
      ]);
      expect(overrides.ignore).toEqual(['*.tmp', 'dist/']);
    });

    it('should handle missing override files', async () => {
      mockFs.readFile.mockRejectedValue({ code: 'ENOENT' });

      const manager = new GitignoreManager({}, testBasePath);
      const overrides = await manager.readOverrides();

      expect(overrides.keep).toEqual([]);
      expect(overrides.ignore).toEqual([]);
      expect(overrides.config).toEqual([]);
    });

    it('should include config-based overrides', async () => {
      mockFs.readFile.mockRejectedValue({ code: 'ENOENT' });

      const config: Partial<GitignoreConfig> = {
        alwaysKeep: ['important.txt'],
        alwaysIgnore: ['*.temp'],
      };
      const manager = new GitignoreManager(config, testBasePath);
      const overrides = await manager.readOverrides();

      expect(overrides.keep).toEqual(['important.txt']);
      expect(overrides.config).toEqual(['*.temp']);
    });

    it('should cache overrides', async () => {
      mockFs.readFile.mockRejectedValue({ code: 'ENOENT' });

      const manager = new GitignoreManager({}, testBasePath);
      await manager.readOverrides();
      await manager.readOverrides(); // Second call

      // Should only read files once
      expect(mockFs.readFile).toHaveBeenCalledTimes(2); // Once for each override file
    });

    it('should clear cache when requested', async () => {
      mockFs.readFile.mockRejectedValue({ code: 'ENOENT' });

      const manager = new GitignoreManager({}, testBasePath);
      await manager.readOverrides();
      manager.clearCache();
      await manager.readOverrides();

      // Should read files twice due to cache clear
      expect(mockFs.readFile).toHaveBeenCalledTimes(4);
    });
  });

  describe('shouldIgnore', () => {
    it('should return false when disabled', () => {
      const manager = new GitignoreManager({ enabled: false });
      expect(manager.shouldIgnore('.cursor/rules/test.mdc')).toBe(false);
    });

    it('should return true for generated files by default', () => {
      const manager = new GitignoreManager({}, testBasePath);
      expect(manager.shouldIgnore('.cursor/rules/test.mdc')).toBe(true);
    });

    it('should respect keep patterns', async () => {
      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.rulesetkeep')) {
          return '.cursor/rules/important.mdc';
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      await manager.readOverrides(); // Load overrides

      expect(manager.shouldIgnore('.cursor/rules/important.mdc')).toBe(false);
      expect(manager.shouldIgnore('.cursor/rules/other.mdc')).toBe(true);
    });

    it('should respect ignore patterns', async () => {
      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.rulesetignore')) {
          return '*.tmp';
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      await manager.readOverrides(); // Load overrides

      expect(manager.shouldIgnore('file.tmp')).toBe(true);
      expect(manager.shouldIgnore('file.js')).toBe(true); // Default behavior
    });
  });

  describe('edge cases and error handling', () => {
    it('should handle custom comment prefix', async () => {
      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.gitignore')) {
          return '';
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager(
        {
          commentPrefix: 'MyTool',
        },
        testBasePath
      );

      await manager.updateGitignore(['.cursor/rules/test.mdc']);

      const writeCall = mockFs.writeFile.mock.calls.find(
        (call) => call[0] === path.join(testBasePath, '.gitignore')
      );
      const writtenContent = writeCall![1] as string;
      expect(writtenContent).toContain('# START MyTool Generated Files');
      expect(writtenContent).toContain('# END MyTool Generated Files');
    });

    it('should handle duplicate paths', async () => {
      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.gitignore')) {
          return '';
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      const result = await manager.updateGitignore([
        '.cursor/rules/test.mdc',
        './cursor/rules/test.mdc', // Same file, different path format
        '.cursor/rules/test.mdc', // Exact duplicate
      ]);

      expect(result.added).toEqual(['.cursor/rules/test.mdc']);
    });

    it('should handle path normalization across platforms', async () => {
      mockFs.readFile.mockImplementation(async (filePath: string) => {
        if (filePath.endsWith('.gitignore')) {
          return '';
        }
        throw { code: 'ENOENT' };
      });

      const manager = new GitignoreManager({}, testBasePath);
      const result = await manager.updateGitignore([
        '.cursor\\rules\\test.mdc', // Windows path
        '.cursor/rules/test.mdc', // Unix path
      ]);

      expect(result.added).toEqual(['.cursor/rules/test.mdc']);
    });
  });
});
