/**
 * Tests for gitignore utility functions
 */

import {
  normalizeGitignorePath,
  matchesAnyPattern,
  matchesPattern,
  parseOverrideFile,
  parseGitignoreContent,
  generateManagedBlock,
  rebuildGitignoreContent,
  sortAndDedupePaths,
  DEFAULT_MANAGED_BLOCK_CONFIG,
} from '../utils';

describe('normalizeGitignorePath', () => {
  const originalCwd = process.cwd();
  
  beforeEach(() => {
    process.chdir('/test/base');
  });
  
  afterEach(() => {
    process.chdir(originalCwd);
  });

  it('should normalize absolute paths to relative', () => {
    expect(normalizeGitignorePath('/test/base/src/file.ts', '/test/base')).toBe('src/file.ts');
  });

  it('should handle already relative paths', () => {
    expect(normalizeGitignorePath('src/file.ts')).toBe('src/file.ts');
  });

  it('should convert backslashes to forward slashes', () => {
    expect(normalizeGitignorePath('src\\file.ts')).toBe('src/file.ts');
  });

  it('should remove leading ./', () => {
    expect(normalizeGitignorePath('./src/file.ts')).toBe('src/file.ts');
  });

  it('should handle complex paths', () => {
    expect(normalizeGitignorePath('/test/base/./src/../dist/file.js', '/test/base')).toBe('dist/file.js');
  });
});

describe('matchesPattern', () => {
  it('should match exact paths', () => {
    expect(matchesPattern('src/file.ts', 'src/file.ts')).toBe(true);
    expect(matchesPattern('src/file.ts', 'src/other.ts')).toBe(false);
  });

  it('should match directory patterns', () => {
    expect(matchesPattern('dist/bundle.js', 'dist/')).toBe(true);
    expect(matchesPattern('src/dist/file.js', 'dist/')).toBe(false);
  });

  it('should handle wildcard patterns', () => {
    expect(matchesPattern('file.js', '*.js')).toBe(true);
    expect(matchesPattern('src/file.js', 'src/*.js')).toBe(true);
    expect(matchesPattern('file.ts', '*.js')).toBe(false);
  });

  it('should ignore comment lines', () => {
    expect(matchesPattern('file.js', '# *.js')).toBe(false);
    expect(matchesPattern('file.js', '  # comment')).toBe(false);
  });

  it('should handle complex wildcard patterns', () => {
    expect(matchesPattern('.cursor/rules/test.mdc', '.cursor/rules/*.mdc')).toBe(true);
    expect(matchesPattern('packages/core/dist/index.js', '*/dist/*')).toBe(true);
  });
});

describe('matchesAnyPattern', () => {
  it('should return true if any pattern matches', () => {
    const patterns = ['*.js', 'dist/', 'src/test.ts'];
    expect(matchesAnyPattern('file.js', patterns)).toBe(true);
    expect(matchesAnyPattern('dist/bundle.js', patterns)).toBe(true);
    expect(matchesAnyPattern('src/test.ts', patterns)).toBe(true);
  });

  it('should return false if no patterns match', () => {
    const patterns = ['*.js', 'dist/', 'src/test.ts'];
    expect(matchesAnyPattern('file.ts', patterns)).toBe(false);
    expect(matchesAnyPattern('src/other.ts', patterns)).toBe(false);
  });
});

describe('parseOverrideFile', () => {
  it('should parse valid patterns', () => {
    const content = `
# Comment line
.cursor/rules/important.mdc
dist/

# Another comment
*.log
`;
    const result = parseOverrideFile(content);
    expect(result).toEqual([
      '.cursor/rules/important.mdc',
      'dist/',
      '*.log'
    ]);
  });

  it('should handle empty file', () => {
    expect(parseOverrideFile('')).toEqual([]);
  });

  it('should filter out comments and empty lines', () => {
    const content = `
# This is a comment

.cursor/rules/test.mdc
# Another comment


dist/
`;
    const result = parseOverrideFile(content);
    expect(result).toEqual([
      '.cursor/rules/test.mdc',
      'dist/'
    ]);
  });
});

describe('parseGitignoreContent', () => {
  it('should parse content without managed block', () => {
    const content = `# Regular gitignore
node_modules/
*.log
dist/`;
    
    const result = parseGitignoreContent(content);
    expect(result).toEqual({
      original: content,
      beforeBlock: content,
      afterBlock: '',
      managedPaths: [],
      hasExistingBlock: false,
    });
  });

  it('should parse content with managed block', () => {
    const content = `# Regular gitignore
node_modules/
*.log

# START Rulesets Generated Files
# Generated by Rulesets - do not edit manually
.cursor/rules/test.mdc
.windsurf/rules/test.md
# END Rulesets Generated Files

# More content
dist/`;
    
    const result = parseGitignoreContent(content);
    expect(result.beforeBlock).toBe(`# Regular gitignore
node_modules/
*.log`);
    expect(result.afterBlock).toBe(`# More content
dist/`);
    expect(result.managedPaths).toEqual([
      '.cursor/rules/test.mdc',
      '.windsurf/rules/test.md'
    ]);
    expect(result.hasExistingBlock).toBe(true);
  });

  it('should handle malformed managed blocks', () => {
    const content = `# Regular gitignore
# START Rulesets Generated Files
.cursor/rules/test.mdc
# Missing end comment`;
    
    const result = parseGitignoreContent(content);
    expect(result.hasExistingBlock).toBe(false);
    expect(result.beforeBlock).toBe(content);
  });
});

describe('generateManagedBlock', () => {
  it('should generate properly formatted block', () => {
    const paths = ['.windsurf/rules/test.md', '.cursor/rules/test.mdc'];
    const result = generateManagedBlock(paths);
    
    expect(result).toBe(`# START Rulesets Generated Files
# Generated by Rulesets - do not edit manually
.cursor/rules/test.mdc
.windsurf/rules/test.md
# END Rulesets Generated Files`);
  });

  it('should return empty string for no paths', () => {
    expect(generateManagedBlock([])).toBe('');
  });

  it('should sort paths alphabetically', () => {
    const paths = ['z.txt', 'a.txt', 'm.txt'];
    const result = generateManagedBlock(paths);
    
    expect(result.includes('a.txt\nm.txt\nz.txt')).toBe(true);
  });
});

describe('rebuildGitignoreContent', () => {
  it('should rebuild content with new managed block', () => {
    const state = {
      original: 'original',
      beforeBlock: 'node_modules/',
      afterBlock: 'dist/',
      managedPaths: [],
      hasExistingBlock: false,
    };
    
    const newPaths = ['.cursor/rules/test.mdc'];
    const result = rebuildGitignoreContent(state, newPaths);
    
    expect(result).toContain('node_modules/');
    expect(result).toContain('# START Rulesets Generated Files');
    expect(result).toContain('.cursor/rules/test.mdc');
    expect(result).toContain('# END Rulesets Generated Files');
    expect(result).toContain('dist/');
  });

  it('should handle empty before and after blocks', () => {
    const state = {
      original: '',
      beforeBlock: '',
      afterBlock: '',
      managedPaths: [],
      hasExistingBlock: false,
    };
    
    const newPaths = ['.cursor/rules/test.mdc'];
    const result = rebuildGitignoreContent(state, newPaths);
    
    expect(result).toBe(`# START Rulesets Generated Files
# Generated by Rulesets - do not edit manually
.cursor/rules/test.mdc
# END Rulesets Generated Files`);
  });

  it('should handle no paths to add', () => {
    const state = {
      original: 'node_modules/',
      beforeBlock: 'node_modules/',
      afterBlock: '',
      managedPaths: [],
      hasExistingBlock: false,
    };
    
    const result = rebuildGitignoreContent(state, []);
    expect(result).toBe('node_modules/');
  });
});

describe('sortAndDedupePaths', () => {
  it('should sort and remove duplicates', () => {
    const paths = ['z.txt', 'a.txt', 'z.txt', 'm.txt', 'a.txt'];
    const result = sortAndDedupePaths(paths);
    
    expect(result).toEqual(['a.txt', 'm.txt', 'z.txt']);
  });

  it('should handle empty array', () => {
    expect(sortAndDedupePaths([])).toEqual([]);
  });

  it('should normalize paths before deduping', () => {
    const paths = ['./src/file.ts', 'src/file.ts', '.\\src\\file.ts'];
    const result = sortAndDedupePaths(paths);
    
    expect(result).toEqual(['src/file.ts']);
  });
});