/**
 * Utility functions for gitignore management
 * Provides path manipulation, file parsing, and content management utilities
 */

import { isAbsolute, relative } from 'node:path';
import type { GitignoreState, ManagedBlockConfig } from './types';

// Regex constants at top level for performance
const COMMENT_LINE_REGEX = /^\s*#.*$/;
const TRAILING_NEWLINES_REGEX = /\n+$/;
const LEADING_NEWLINES_REGEX = /^\n+/;

/**
 * Default configuration for managed gitignore blocks
 */
export const DEFAULT_MANAGED_BLOCK_CONFIG: ManagedBlockConfig = {
  startComment: '# START Rulesets Generated Files',
  endComment: '# END Rulesets Generated Files',
  headerText: 'Generated by Rulesets - do not edit manually',
};

/**
 * Normalize a file path to POSIX-style path
 * @param filePath - Path to normalize
 * @param basePath - Base path to make relative from (optional)
 * @returns Normalized POSIX-style path
 */
export function normalizeGitignorePath(
  filePath: string,
  basePath?: string
): string {
  // Convert to relative path only if basePath is provided and filePath is absolute
  const relativePath =
    isAbsolute(filePath) && basePath !== undefined
      ? relative(basePath, filePath)
      : filePath;

  // Convert to POSIX-style path separators and normalize backslashes
  let posixPath = relativePath.replace(/\\/g, '/');

  // Remove leading ./ if present
  if (posixPath.startsWith('./')) posixPath = posixPath.slice(2);

  return posixPath;
}

/**
 * Check if a path matches any pattern in a list of glob-style patterns
 * @param filePath - Path to check
 * @param patterns - Array of patterns to match against
 * @returns True if path matches any pattern
 */
export function matchesAnyPattern(
  filePath: string,
  patterns: readonly string[]
): boolean {
  const normalizedPath = normalizeGitignorePath(filePath);

  for (const pattern of patterns) {
    if (matchesPattern(normalizedPath, pattern)) {
      return true;
    }
  }

  return false;
}

/**
 * Check if a path matches a specific glob-style pattern
 * @param filePath - Path to check
 * @param pattern - Pattern to match against
 * @returns True if path matches pattern
 */
export function matchesPattern(filePath: string, pattern: string): boolean {
  // Remove leading comments and whitespace
  const cleanPattern = pattern.replace(COMMENT_LINE_REGEX, '').trim();
  if (!cleanPattern) {
    return false;
  }

  // Exact match
  if (cleanPattern === filePath) {
    return true;
  }

  // Directory match (pattern ends with /)
  if (cleanPattern.endsWith('/') && filePath.startsWith(cleanPattern)) {
    return true;
  }

  // Simple wildcard support for basic patterns
  if (cleanPattern.includes('*')) {
    const regexPattern = cleanPattern
      .replace(/[.+^${}()|[\]\\]/g, '\\$&') // Escape regex special chars
      .replace(/\*/g, '.*'); // Convert * to .*

    try {
      return new RegExp(`^${regexPattern}$`).test(filePath);
    } catch {
      // If regex fails, fall back to simple string match
      return cleanPattern.replace(/\*/g, '') === filePath.replace(/\*/g, '');
    }
  }

  return false;
}

/**
 * Parse override content into an array of patterns
 * @param content - Content string to parse
 * @returns Array of valid patterns (excluding comments and empty lines)
 */
export function parseOverrideContent(content: string): string[] {
  const lines = content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => normalizeGitignorePath(line));

  return lines;
}

/**
 * Parse override file content into an object with success status
 * @param pathOrContent - File path or content string to parse
 * @returns Object with success status, patterns array, and any errors
 */
export function parseOverrideFile(pathOrContent: string): {
  success: boolean;
  patterns: string[];
  errors: string[];
} {
  try {
    // If argument looks like a filepath, try to read it. Otherwise treat as content
    const isFileInput =
      pathOrContent.includes('/') || pathOrContent.includes('\\');
    let content: string;

    if (isFileInput) {
      // Try to read as file
      try {
        const fs = require('node:fs');
        content = fs.readFileSync(pathOrContent, 'utf8');
      } catch {
        // If file reading fails and it's a file path, return empty patterns
        return { success: true, patterns: [], errors: [] };
      }
    } else {
      // Treat as content
      content = pathOrContent;
    }

    const patterns = parseOverrideContent(content);
    return { success: true, patterns, errors: [] };
  } catch (error) {
    return {
      success: false,
      patterns: [],
      errors: [
        error instanceof Error
          ? error.message
          : 'Failed to parse override file',
      ],
    };
  }
}

/**
 * Parse .gitignore content and extract managed block information
 * @param content - .gitignore file content
 * @param config - Configuration for managed block
 * @returns GitignoreState with parsed information
 */
export function parseGitignoreContent(
  content: string,
  config: ManagedBlockConfig = DEFAULT_MANAGED_BLOCK_CONFIG
): GitignoreState {
  const lines = content.split('\n');
  const startIndex = lines.findIndex(
    (line) => line.trim() === config.startComment
  );
  const endIndex = lines.findIndex((line) => line.trim() === config.endComment);

  if (startIndex === -1 || endIndex === -1 || startIndex >= endIndex) {
    // No managed block found
    return {
      original: content,
      beforeBlock: content,
      afterBlock: '',
      managedPaths: [],
      hasExistingBlock: false,
    };
  }

  const beforeBlock = lines.slice(0, startIndex).join('\n');
  const afterBlock = lines.slice(endIndex + 1).join('\n');
  const managedLines = lines.slice(startIndex + 1, endIndex);

  // Extract paths from managed block (excluding comments and empty lines)
  const managedPaths = managedLines
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => normalizeGitignorePath(line));

  return {
    original: content,
    beforeBlock: beforeBlock.replace(TRAILING_NEWLINES_REGEX, ''), // Remove trailing newlines
    afterBlock: afterBlock.replace(LEADING_NEWLINES_REGEX, ''), // Remove leading newlines
    managedPaths,
    hasExistingBlock: true,
  };
}

/**
 * Generate managed block content with sorted paths
 * @param paths - Array of paths to include in the block
 * @param config - Configuration for managed block
 * @returns Generated block content
 */
export function generateManagedBlock(
  paths: readonly string[],
  config: ManagedBlockConfig = DEFAULT_MANAGED_BLOCK_CONFIG
): string {
  if (paths.length === 0) {
    return '';
  }

  const sortedPaths = [...paths].sort();
  const blockLines = [
    config.startComment,
    ...(config.headerText ? [`# ${config.headerText}`] : []),
    ...sortedPaths,
    config.endComment,
  ];

  return blockLines.join('\n');
}

/**
 * Rebuild complete .gitignore content with new managed block
 * @param state - Current gitignore state
 * @param newPaths - New paths to include in managed block
 * @param config - Configuration for managed block
 * @returns Complete new .gitignore content
 */
export function rebuildGitignoreContent(
  state: GitignoreState,
  newPaths: readonly string[],
  config: ManagedBlockConfig = DEFAULT_MANAGED_BLOCK_CONFIG
): string {
  const parts: string[] = [];

  // Add content before managed block
  if (state.beforeBlock) {
    parts.push(state.beforeBlock);
  }

  // Add managed block if there are paths to include
  const managedBlock = generateManagedBlock(newPaths, config);
  if (managedBlock) {
    // Ensure proper spacing around the block
    if (state.beforeBlock && !state.beforeBlock.endsWith('\n')) {
      parts.push('');
    }
    parts.push(managedBlock);
    if (state.afterBlock && !state.afterBlock.startsWith('\n')) {
      parts.push('');
    }
  }

  // Add content after managed block
  if (state.afterBlock) {
    parts.push(state.afterBlock);
  }

  return parts.join('\n');
}

/**
 * Sort and deduplicate an array of file paths
 * @param paths - Array of paths to process
 * @returns Sorted and deduplicated array
 */
export function sortAndDedupePaths(paths: readonly string[]): string[] {
  const normalizedPaths = paths.map((p) => normalizeGitignorePath(p));
  const uniquePaths = Array.from(new Set(normalizedPaths));
  return uniquePaths.sort();
}
