#!/usr/bin/env bun

/**
 * Rulesets Sandbox
 *
 * Interactive environment for testing and exploring Rulesets compilation.
 * This is a standalone app that provides a safe space to experiment.
 */

import { existsSync } from 'node:fs';
import { basename, resolve } from 'node:path';
import chalk from 'chalk';
import { Command } from 'commander';

const program = new Command();

// Simple logger for sandbox
const logger = {
  info: (message: string, ...args: unknown[]) =>
    console.log(chalk.blue('ℹ'), message, ...args),
  error: (message: string, ...args: unknown[]) =>
    console.log(chalk.red('✗'), message, ...args),
  warn: (message: string, ...args: unknown[]) =>
    console.log(chalk.yellow('⚠'), message, ...args),
  success: (message: string, ...args: unknown[]) =>
    console.log(chalk.green('✓'), message, ...args),
};

// Simple rule compilation for demonstration purposes
async function simpleCompileRuleset(
  inputFile: string,
  baseDir = '.'
): Promise<void> {
  const content = await Bun.file(inputFile).text();
  const fileName = basename(inputFile, '.rule.md').replace('.ruleset', '');

  // Create realistic output structure
  const { mkdirSync } = await import('node:fs');
  mkdirSync(`${baseDir}/.cursor/rules`, { recursive: true });
  mkdirSync(`${baseDir}/.windsurf`, { recursive: true });

  // Simple block extraction (basic demo)
  const instructionsMatch = content.match(
    /{{instructions}}([\s\S]*?){{\/instructions}}/
  );
  const examplesMatch = content.match(/{{examples}}([\s\S]*?){{\/examples}}/);

  const instructions = instructionsMatch
    ? instructionsMatch[1].trim()
    : 'No instructions provided';
  const examples = examplesMatch
    ? examplesMatch[1].trim()
    : 'No examples provided';

  // Generate realistic provider outputs
  const cursorOutput = `# ${fileName}

${instructions}

## Examples

${examples}

`;

  const claudeOutput = `# ${fileName}

${instructions}

${examples}

---
Generated by Rulesets Sandbox ruleset-v0.1-beta
`;

  const windsurfOutput = claudeOutput;
  const ampOutput = claudeOutput;
  const codexOutput = claudeOutput;

  // Write to realistic locations
  await Bun.write(`${baseDir}/.cursor/rules/${fileName}.mdc`, cursorOutput);
  await Bun.write(`${baseDir}/CLAUDE.md`, claudeOutput);
  await Bun.write(`${baseDir}/.windsurf/rules.md`, windsurfOutput);
  await Bun.write(`${baseDir}/AGENT.md`, ampOutput);
  await Bun.write(`${baseDir}/AGENTS.md`, codexOutput);
}

program
  .name('rulesets-sandbox')
  .description('Interactive sandbox for Rulesets compilation')
  .version('0.1.0');

program
  .command('run [file]')
  .description('Compile ruleset(s) to realistic project locations')
  .option('-d, --dir <dir>', 'Project base directory', '.')
  .option('--verbose', 'Enable verbose logging')
  .action(async (file: string | undefined, options) => {
    console.log(chalk.cyan('🎮 Rulesets Sandbox'));
    console.log(chalk.gray('📤 Project directory:'), resolve(options.dir));
    console.log('');

    try {
      let filesToCompile: string[] = [];

      if (file) {
        // Single file mode
        const inputFile = resolve(file);
        if (!existsSync(inputFile)) {
          logger.error(`❌ File not found: ${file}`);
          process.exit(1);
        }
        filesToCompile = [inputFile];
        console.log(chalk.gray('📁 Compiling:'), file);
      } else {
        // Compile all rulesets in .agent/src/
        try {
          const { readdirSync } = await import('node:fs');

          if (!existsSync('.agent/src')) {
            logger.warn('No .agent/src/ directory found');
            console.log('');
            console.log(
              chalk.yellow('💡 Create rulesets with:'),
              'bun run start init <name>'
            );
            return;
          }

          const allFiles = readdirSync('.agent/src');
          const rulesets = allFiles
            .filter((f) => f.endsWith('.rule.md'))
            .map((f) => `.agent/src/${f}`);

          if (rulesets.length === 0) {
            logger.warn('No rulesets found in .agent/src/');
            console.log('');
            console.log(
              chalk.yellow('💡 Create rulesets with:'),
              'bun run start init <name>'
            );
            return;
          }

          filesToCompile = rulesets.map((f) => resolve(f));
          console.log(chalk.gray('📁 Compiling all rulesets:'));
          for (const ruleset of rulesets) {
            console.log(chalk.gray('  •'), ruleset);
          }
        } catch (error) {
          logger.error('❌ Error scanning for rulesets:', error);
          process.exit(1);
        }
      }

      console.log('');

      // Compile each file
      const allGeneratedFiles = new Set<string>();

      for (const inputFile of filesToCompile) {
        const fileName = basename(inputFile, '.rule.md').replace(
          '.ruleset',
          ''
        );
        console.log(chalk.blue('🔨 Processing:'), fileName);

        await simpleCompileRuleset(inputFile, options.dir);

        // Track generated files
        const expectedFiles = [
          '.cursor/rules/' + fileName + '.mdc',
          'CLAUDE.md',
          '.windsurf/rules.md',
          'AGENT.md',
          'AGENTS.md',
        ];

        expectedFiles.forEach((f) => allGeneratedFiles.add(f));
      }

      console.log('');
      console.log(
        chalk.green('✨ All rules compiled to realistic project structure!')
      );
      console.log('');
      console.log(chalk.gray('📂 Generated files:'));

      for (const file of Array.from(allGeneratedFiles).sort()) {
        const fullPath = resolve(options.dir, file);
        if (existsSync(fullPath)) {
          console.log(chalk.green('  ✅'), file);
        } else {
          console.log(chalk.red('  ❌'), file);
        }
      }
    } catch (error) {
      console.log('');
      logger.error('❌ Sandbox compilation failed:', error);
      process.exit(1);
    }
  });

program
  .command('examples')
  .description('List available rulesets')
  .action(async () => {
    console.log(chalk.cyan('🎮 Available Rulesets'));
    console.log('');

    try {
      const rulesets = await Array.fromAsync(
        new Bun.Glob('.agent/src/*.rule.md').scan('.')
      );

      const legacyExamples = await Array.fromAsync(
        new Bun.Glob('examples/*.ruleset.md').scan('.')
      );

      if (rulesets.length === 0 && legacyExamples.length === 0) {
        console.log(chalk.yellow('No rulesets found.'));
        console.log('');
        console.log('Create rulesets in .agent/src/');
        console.log('Example: .agent/src/my-rules.rule.md');
      } else {
        if (rulesets.length > 0) {
          console.log(chalk.blue('🏗️  Project Rulesets (.agent/src/):'));
          for (const ruleset of rulesets) {
            console.log(chalk.green('  📝'), ruleset);
          }
          console.log('');
        }

        if (legacyExamples.length > 0) {
          console.log(chalk.blue('📚 Legacy Examples (examples/):'));
          for (const example of legacyExamples) {
            console.log(chalk.green('  📝'), example);
          }
          console.log('');
        }

        console.log(
          chalk.gray('Run with:'),
          'bun run start run <ruleset-file>'
        );
      }
    } catch (error) {
      console.log(chalk.red('Error listing rulesets:'), error);
    }
  });

program
  .command('clean')
  .description('Clean generated rules from project')
  .action(async () => {
    console.log(chalk.cyan('🧹 Cleaning generated rules...'));

    try {
      const { rmSync } = await import('node:fs');

      const filesToClean = [
        '.cursor/rules',
        '.windsurf/rules.md',
        'CLAUDE.md',
        'AGENT.md',
        'AGENTS.md',
      ];

      let cleaned = 0;
      for (const file of filesToClean) {
        if (existsSync(file)) {
          rmSync(file, { recursive: true });
          cleaned++;
          console.log(chalk.gray('  🗑️ Removed:'), file);
        }
      }

      if (cleaned > 0) {
        console.log(chalk.green(`✅ Cleaned ${cleaned} generated files!`));
      } else {
        console.log(chalk.yellow('No generated files found to clean.'));
      }
    } catch (error) {
      console.log(chalk.red('❌ Clean failed:'), error);
    }
  });

program
  .command('structure')
  .description('Show the current project structure')
  .action(async () => {
    console.log(chalk.cyan('🏗️  Sandbox Project Structure'));
    console.log('');

    const structure = [
      '📁 .',
      '├── 🤖 .agent/',
      '│   ├── 📝 src/',
      '│   │   ├── typescript-standards.rule.md',
      '│   │   ├── react-best-practices.rule.md',
      '│   │   └── project-conventions.rule.md',
      '│   └── ⚙️  ruleset.config.jsonc',
      '├── 📱 apps/',
      '│   ├── web/ (Next.js)',
      '│   └── api/ (Fastify)',
      '├── 📦 packages/',
      '│   ├── ui/ (React components)',
      '│   └── utils/ (Shared utilities)',
      '├── 🎯 .cursor/rules/ (Generated)',
      '├── 🌊 .windsurf/rules.md (Generated)',
      '├── 📄 CLAUDE.md (Generated)',
      '├── 📄 AGENT.md (Generated)',
      '└── 📄 AGENTS.md (Generated)',
    ];

    for (const line of structure) {
      console.log(line);
    }

    console.log('');
    console.log(chalk.blue('💡 Tips:'));
    console.log('  • Edit rulesets in .agent/src/');
    console.log(
      '  • Run compilation with: bun run start run .agent/src/<file>'
    );
    console.log('  • Copy this structure to your real projects!');
  });

program
  .command('init')
  .description('Create a new ruleset file in .agent/src/')
  .argument('[name]', 'Name for the ruleset file', 'my-rules')
  .action(async (name: string) => {
    const fileName = `.agent/src/${name}.rule.md`;

    if (existsSync(fileName)) {
      console.log(chalk.yellow('⚠️  File already exists:'), fileName);
      return;
    }

    const titleCase = name
      .split('-')
      .map((w) => w[0].toUpperCase() + w.slice(1))
      .join(' ');

    const sampleContent = `---
ruleset:
  version: 0.1.0
  
title: "${titleCase}"
description: "Custom ruleset created in sandbox"

providers:
  cursor:
    enabled: true
  claude-code:
    enabled: true
  windsurf:
    enabled: true
---

# ${titleCase}

{{instructions}}
- Add your coding standards here
- Define your team's best practices
- Include specific guidelines
- Follow consistent patterns
{{/instructions}}

{{examples}}
\`\`\`typescript
// Add code examples here
const example = "This shows good practices";

// Show both good and bad examples
// ✅ Good: Clear and descriptive
function calculateTotalPrice(items: Item[]): number {
  return items.reduce((total, item) => total + item.price, 0);
}

// ❌ Bad: Unclear and untyped
function calc(arr) {
  return arr.reduce((a, b) => a + b.price, 0);
}
\`\`\`
{{/examples}}
`;

    try {
      const { mkdirSync } = await import('node:fs');
      mkdirSync('.agent/src', { recursive: true });
      await Bun.write(fileName, sampleContent);
      console.log(chalk.green('✅ Created:'), fileName);
      console.log('');
      console.log(chalk.gray('Run with:'), `bun run start run ${fileName}`);
      console.log(
        chalk.gray('Edit the file to add your specific rules and examples!')
      );
    } catch (error) {
      console.log(chalk.red('❌ Failed to create file:'), error);
    }
  });

// Default help if no command provided
if (process.argv.length <= 2) {
  program.help();
}

program.parse();
